---
- name: remove existing {{ docker_logstash_name }} files and directories
  file:
    path: "{{ logstash_path }}"
    state: absent

- name: create {{ docker_logstash_name }} pipeline directory
  become: true
  file:
    path: "{{ logstash_path }}/pipeline"
    state: directory

- name: create {{ docker_logstash_name }} pipeline file
  become: true
  template:
    dest: "{{ logstash_path }}/pipeline/logstash.conf"
    src: "templates/logstash.conf.j2"

- name: remove existing {{ docker_logstash_name }} container
  docker_container:
    image: "{{ docker_logstash_image }}"
    name: "{{ docker_logstash_name }}"
    state: absent    

- name: deploy {{ docker_logstash_name }} container
  docker_container:
    name: "{{ docker_logstash_name }}"
    image: "{{ docker_logstash_image }}"
    state: started
    exposed_ports: "{{ docker_logstash_expose }}"
    ports: "{{ docker_logstash_ports }}"
    restart_policy: unless-stopped
    volumes: "{{ logstash_path }}/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
 